version: '3.8'

services:
  # FastAPI Gateway Service
  fastapi-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-gateway
    ports:
      - "8080:8000"
    environment:
      - LOCALAI_HOST=localai
      - LOCALAI_PORT=8080
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - localai
      - qdrant
      - postgres
      - redis
    networks:
      - llm-network

  # LocalAI Service
  localai:
    image: localai/localai:latest-aio-cpu
    container_name: localai
    ports:
      - "8081:8080"
    environment:
      - MODELS_PATH=/models
    volumes:
      - localai-data:/mnt/assets/models/llm
    networks:
      - llm-network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - llm-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=con_selfrag
      - POSTGRES_USER=con_selfrag
      - POSTGRES_PASSWORD=con_selfrag_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - llm-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - llm-network

volumes:
  localai-data:
    driver: local
  qdrant-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  llm-network:
    driver: bridge