services:
  # Frontend service: Customize for your chosen framework
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-3000}:80"  # Adjust port based on your framework
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - llm-network

  # Frontend development service: Customize for your framework's dev server
  # Uncomment and modify this section once you've implemented your frontend
  # frontend-dev:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev  # Create this for your framework
  #   env_file:
  #     - .env
  #   ports:
  #     - "${FRONTEND_DEV_PORT:-3001}:3000"  # Adjust based on your framework
  #   environment:
  #     - NODE_ENV=development
  #     - BACKEND_URL=${BACKEND_URL:-http://backend-dev:8000}
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules  # Adjust based on your framework
  #   depends_on:
  #     - backend-dev
  #   profiles: ["dev"]
  #   networks:
  #     - llm-network

networks:
  llm-network:
    driver: bridge
