"""Add memory_logs table

Revision ID: 003_add_memory_logs_table
Revises: 002_auth_enhancements
Create Date: 2025-08-05 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003_add_memory_logs_table'
down_revision: Union[str, None] = '002_auth_enhancements'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_logs_id', 'memory_logs', ['id'], unique=False)
    op.create_index('ix_memory_logs_timestamp', 'memory_logs', ['timestamp'], unique=False)
    op.create_index('ix_memory_logs_user_id', 'memory_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_logs_user_id', table_name='memory_logs')
    op.drop_index('ix_memory_logs_timestamp', table_name='memory_logs')
    op.drop_index('ix_memory_logs_id', table_name='memory_logs')
    op.drop_table('memory_logs')
    # ### end Alembic commands ###
